### ISSUE TITLE
debian/ubuntu_opal_pba

### ISSUE THREAD

**Issue by kendallgreen** [konstmonst/arch_opal_pba#1]
Can you suggest or make a debian/ubuntu version of your tools.  I have a laptop with a SED SSD  that has  windows 10, debian and ubuntu distros on it that I would like to encrypt using sedutil and PBA

**Comment by konstmonst** [comment]
Hi, I can build an share the Image I currently use on my laptop. The boot image does not have to be a specific distribution. It just need to be linux.

**Comment by kendallgreen** [comment]
my laptop has both Windows 10 home, ubuntu and debian distributions. I
am cloning the hard drive to a Micron M500 240 GB drive which I hope
to encrypt.  I use grub2 to choose which OS to boot.

On 4/10/16, konstmonst notifications@github.com wrote:

> Hi, I can build an share the Image I currently use on my laptop. The boot
> image does not have to be a specific distribution. It just need to be
> linux.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/konstmonst/arch_opal_pba/issues/1#issuecomment-207948047

## 

Kendall B. Green DC70FEBB

**Comment by konstmonst** [comment]
I made an image here, you can use it (if you trust me)
https://drive.google.com/file/d/0Bw4TQ1RG3NQjU1BzQVhvMVZ4Znc/view?usp=sharing
You should build  one yourself though. I will use a more generic tool to make the image when the time allows, it's just that mkinitcpio is quite flexible in that respect.

**Comment by kendallgreen** [comment]
I trust you, but the image doesn't load from a USB drive.  Do I need to modify the grub.cfg folder.  My laptop is old and doesn't use UEFI rather legacy bios from ami.  I cloned your git folder and am willing to build a pba.img on my laptop using Ubuntu 14.04.  I need some help.  can I use charles anderson's buildroot  https://github.com/canderson/buildroot-linuxpba/tree/master?

**Comment by konstmonst** [comment]
Hi, I did the image for UEFI, because the original build process from 
https://github.com/Drive-Trust-Alliance/sedutil didn't work for me. 
UEFI64 is the only target I had in mind.

The easiest way to modify my Image for BIOS Mode would be to mount one 
of the generated Image Partitions and to do grub-install 
--target=i386-pc --boot-directory=/image/partition/mountpoint.

You will also have to try some times untill you figure it out.
I don't really use non UEFI Boot anywhere nor do I have the time  to 
implement it (family and work), however you may ask me specific 
questions and I will try to answer as time allows.

Best Regards,
Konstantin.

**Comment by kendallgreen** [comment]
close
